/**
 * SQF Sanitizer - Additional security layer
 */

export class SQFSanitizer {
  /**
   * Sanitize variable names to prevent injection
   */
  sanitizeVariableName(name: string): string {
    // Only allow alphanumeric and underscore
    return name.replace(/[^a-zA-Z0-9_]/g, '');
  }

  /**
   * Sanitize string literals to prevent injection
   */
  sanitizeString(str: string): string {
    // Escape quotes and prevent script injection
    return str.replace(/"/g, '""').replace(/'/g, "''");
  }

  /**
   * Convert double quotes to single quotes in SQF code
   * Handles nested quotes by doubling single quotes
   */
  convertQuotes(sqf: string): string {
    // First, double any existing single quotes within double-quoted strings
    // Then replace double quotes with single quotes
    let result = '';
    let inString = false;
    let i = 0;

    while (i < sqf.length) {
      const char = sqf[i];

      if (char === '"') {
        // Check for escaped double quote ("")
        if (i + 1 < sqf.length && sqf[i + 1] === '"') {
          // Escaped double quote inside a string - convert to doubled single quote
          result += "''";
          i += 2;
          continue;
        }

        // Toggle string state and convert to single quote
        inString = !inString;
        result += "'";
        i++;
      } else if (char === "'" && inString) {
        // Single quote inside a string needs to be doubled
        result += "''";
        i++;
      } else {
        result += char;
        i++;
      }
    }

    return result;
  }

  /**
   * Remove potentially dangerous inline comments
   */
  removeInlineComments(sqf: string): string {
    // Remove single-line comments but preserve structure
    return sqf.split('\n').map(line => {
      // Don't remove comments that are part of strings
      const commentIndex = line.indexOf('//');
      if (commentIndex !== -1) {
        // Basic check: if we're not in a string, remove comment
        const beforeComment = line.substring(0, commentIndex);
        const quoteCount = (beforeComment.match(/"/g) || []).length;
        if (quoteCount % 2 === 0) {
          return beforeComment;
        }
      }
      return line;
    }).join('\n');
  }

  /**
   * Wrap code in safe execution context
   */
  wrapInSafeContext(sqf: string): string {
    // Wrap in try-catch equivalent for SQF
    return `
// LLM-Generated Code - Auto-wrapped for safety
try {
${sqf}
} catch {
  diag_log format ["[LLMGM] Error executing generated SQF: %1", _exception];
};
`.trim();
  }

  /**
   * Add execution metadata comments
   */
  addMetadata(sqf: string, metadata: { timestamp: number; action: string; reasoning?: string }): string {
    const header = `
// Generated by LLM Game Master
// Timestamp: ${new Date(metadata.timestamp).toISOString()}
// Action: ${metadata.action}
${metadata.reasoning ? `// Reasoning: ${metadata.reasoning}` : ''}
// ============================================
`.trim();

    return `${header}\n\n${sqf}`;
  }
}

export const sqfSanitizer = new SQFSanitizer();
