/**
 * SQF Sanitizer - Additional security layer
 */

export class SQFSanitizer {
  /**
   * Sanitize variable names to prevent injection
   */
  sanitizeVariableName(name: string): string {
    // Only allow alphanumeric and underscore
    return name.replace(/[^a-zA-Z0-9_]/g, '');
  }

  /**
   * Sanitize string literals to prevent injection
   */
  sanitizeString(str: string): string {
    // Escape quotes and prevent script injection
    return str.replace(/"/g, '""').replace(/'/g, "''");
  }

  /**
   * Remove potentially dangerous inline comments
   */
  removeInlineComments(sqf: string): string {
    // Remove single-line comments but preserve structure
    return sqf.split('\n').map(line => {
      // Don't remove comments that are part of strings
      const commentIndex = line.indexOf('//');
      if (commentIndex !== -1) {
        // Basic check: if we're not in a string, remove comment
        const beforeComment = line.substring(0, commentIndex);
        const quoteCount = (beforeComment.match(/"/g) || []).length;
        if (quoteCount % 2 === 0) {
          return beforeComment;
        }
      }
      return line;
    }).join('\n');
  }

  /**
   * Wrap code in safe execution context
   */
  wrapInSafeContext(sqf: string): string {
    // Wrap in try-catch equivalent for SQF
    return `
// LLM-Generated Code - Auto-wrapped for safety
try {
${sqf}
} catch {
  diag_log format ["[LLMGM] Error executing generated SQF: %1", _exception];
};
`.trim();
  }

  /**
   * Full sanitization pipeline for SQF code
   */
  sanitize(sqf: string): string {
    let sanitized = this.removeInlineComments(sqf);
    sanitized = this.wrapInSafeContext(sanitized);
    return sanitized;
  }

  /**
   * Add execution metadata comments
   */
  addMetadata(sqf: string, metadata: { timestamp: number; action: string; reasoning?: string }): string {
    const header = `
// Generated by LLM Game Master
// Timestamp: ${new Date(metadata.timestamp).toISOString()}
// Action: ${metadata.action}
${metadata.reasoning ? `// Reasoning: ${metadata.reasoning}` : ''}
// ============================================
`.trim();

    return `${header}\n\n${sqf}`;
  }
}

export const sqfSanitizer = new SQFSanitizer();
