/**
 * SQF Validator - Security-critical component
 * Validates and sanitizes SQF code generated by LLMs
 */

import { ValidationResult, SecurityResult } from '../game-state/types';

/**
 * Forbidden patterns that should never appear in LLM-generated SQF
 * These are security-critical and must be blocked
 */
const FORBIDDEN_PATTERNS = [
  // Mission control - never allow ending/failing missions
  /endMission/i,
  /failMission/i,
  /forceEnd/i,
  
  // Process control
  /terminate/i,
  /exitWith\s*;/i, // exitWith at statement level (not in condition)
  
  // Player harm
  /deleteVehicle\s+player/i,
  /setDamage\s+1\s*;?\s*player/i,
  /player\s+setDamage\s+1/i,
  
  // File operations
  /saveProfileNamespace/i,
  /loadFile/i,
  /preprocessFile/i,
  /callExtension(?!.*"llmgm")/i, // Block callExtension except our own
  
  // Server commands and admin
  /serverCommand/i,
  /admin/i,
  /#kick/i,
  /#ban/i,
  /#shutdown/i,
  
  // Sensitive data exposure
  /systemChat.*password/i,
  /copyToClipboard/i,
  /getPlayerUID/i, // Prevent UID exposure
  
  // Exploit prevention
  /compile\s+preprocessFileLineNumbers/i,
  /call\s+compile/i, // Dangerous dynamic compilation
  
  // Mission file manipulation
  /saveGame/i,
  /loadGame/i,
  
  // Infinite loops (basic detection)
  /while\s*\{\s*true\s*\}\s*do\s*\{[^}]*\}/i,
];

/**
 * Suspicious patterns that should generate warnings
 */
const SUSPICIOUS_PATTERNS = [
  { pattern: /setDamage/i, message: 'Suspicious pattern detected: setDamage' },
  { pattern: /deleteVehicle/i, message: 'Suspicious pattern detected: deleteVehicle' },
  { pattern: /setPos/i, message: 'Suspicious pattern detected: setPos' },
  { pattern: /spawn\s*\{.*while.*\}/i, message: 'Suspicious pattern detected: spawned loops' },
  { pattern: /for\s*".*"\s*from.*to.*step.*do/i, message: 'Suspicious pattern detected: large loops' },
  { pattern: /"[^"]*"/, message: 'Double quotes detected - SQF uses single quotes for strings' },
];

/**
 * Maximum allowed code length
 */
const MAX_CODE_LENGTH = 10000;

/**
 * Maximum nesting depth
 */
const MAX_NESTING_DEPTH = 10;

export class SQFValidator {
  /**
   * Validate SQF syntax (basic checks)
   */
  validateSyntax(sqf: string): ValidationResult {
    const errors: string[] = [];
    const warnings: string[] = [];

    // Check length
    if (sqf.length === 0) {
      errors.push('SQF code is empty');
      return { valid: false, errors, warnings };
    }

    if (sqf.length > MAX_CODE_LENGTH) {
      errors.push(`SQF code exceeds maximum length of ${MAX_CODE_LENGTH} characters`);
    }

    // Check basic syntax balance
    const braceBalance = this.checkBraceBalance(sqf);
    if (braceBalance !== 0) {
      errors.push(`Unbalanced braces (${braceBalance > 0 ? 'opening' : 'closing'} braces mismatch)`);
    }

    const bracketBalance = this.checkBracketBalance(sqf);
    if (bracketBalance !== 0) {
      errors.push(`Unbalanced brackets (${bracketBalance > 0 ? 'opening' : 'closing'} brackets mismatch)`);
    }

    const parenBalance = this.checkParenBalance(sqf);
    if (parenBalance !== 0) {
      errors.push(`Unbalanced parentheses (${parenBalance > 0 ? 'opening' : 'closing'} parentheses mismatch)`);
    }

    // Check nesting depth
    const nestingDepth = this.checkNestingDepth(sqf);
    if (nestingDepth > MAX_NESTING_DEPTH) {
      warnings.push(`Nesting depth (${nestingDepth}) exceeds recommended maximum of ${MAX_NESTING_DEPTH}`);
    }

    // Check for suspicious patterns
    for (const { pattern, message } of SUSPICIOUS_PATTERNS) {
      if (pattern.test(sqf)) {
        warnings.push(message);
      }
    }

    return {
      valid: errors.length === 0,
      errors,
      warnings
    };
  }

  /**
   * Check for security violations
   */
  checkSecurity(sqf: string): SecurityResult {
    const violations: string[] = [];
    const blockedPatterns: string[] = [];

    for (const pattern of FORBIDDEN_PATTERNS) {
      if (pattern.test(sqf)) {
        violations.push(`Forbidden pattern detected: ${pattern.source}`);
        blockedPatterns.push(pattern.source);
      }
    }

    return {
      safe: violations.length === 0,
      violations,
      blockedPatterns
    };
  }

  /**
   * Sanitize SQF code
   */
  sanitize(sqf: string): string {
    // Remove any potential script injection attempts
    let cleaned = sqf;

    // Remove comments that might hide malicious code
    // Keep inline comments for debugging
    cleaned = cleaned.replace(/\/\*[\s\S]*?\*\//g, ''); // Block comments

    // Trim whitespace
    cleaned = cleaned.trim();

    // Ensure code ends with semicolon if it doesn't
    if (cleaned.length > 0 && !cleaned.endsWith(';') && !cleaned.endsWith('}')) {
      cleaned += ';';
    }

    return cleaned;
  }

  /**
   * Perform complete validation
   */
  validate(sqf: string): { valid: boolean; errors: string[]; warnings: string[] } {
    const syntaxResult = this.validateSyntax(sqf);
    const securityResult = this.checkSecurity(sqf);

    const allErrors = [...syntaxResult.errors, ...securityResult.violations];
    const allWarnings = [...syntaxResult.warnings];

    return {
      valid: syntaxResult.valid && securityResult.safe,
      errors: allErrors,
      warnings: allWarnings
    };
  }

  // Helper methods
  private checkBraceBalance(code: string): number {
    let balance = 0;
    for (const char of code) {
      if (char === '{') balance++;
      if (char === '}') balance--;
    }
    return balance;
  }

  private checkBracketBalance(code: string): number {
    let balance = 0;
    for (const char of code) {
      if (char === '[') balance++;
      if (char === ']') balance--;
    }
    return balance;
  }

  private checkParenBalance(code: string): number {
    let balance = 0;
    for (const char of code) {
      if (char === '(') balance++;
      if (char === ')') balance--;
    }
    return balance;
  }

  private checkNestingDepth(code: string): number {
    let maxDepth = 0;
    let currentDepth = 0;
    
    for (const char of code) {
      if (char === '{') {
        currentDepth++;
        maxDepth = Math.max(maxDepth, currentDepth);
      }
      if (char === '}') {
        currentDepth--;
      }
    }
    
    return maxDepth;
  }
}

export const sqfValidator = new SQFValidator();
